---
- name: Install + Launch Metricbeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download filebeat .rpm file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-x86_64.rpm

  - name: Install Metricbeat .rpm
    command: rpm -vi metricbeat-7.6.1-x86_64.rpm
#????
  - name: Drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
#????
    # Use command module
  - name: Config system module
    command: metricbeat modules enable system

  - name: metricbeat setup
    command: metricbeat setup

  - name: Start metricbeat
    command: service metricbeat start

    # Use systemd module
  - name: Start metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes